# Generated by Django 6.0.6 on 2026-06-06 06:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría de Oferta',
                'verbose_name_plural': 'Categorías de Ofertas',
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('nombre_puesto', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=100)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', max_length=20)),
                ('descripcion', models.TextField()),
                ('requisitos', models.TextField()),
                ('habilidades_requeridas', models.TextField()),
                ('experiencia_requerida', models.CharField(max_length=100)),
                ('nivel_educativo', models.CharField(choices=[('secundario', 'Secundario Completo / Bachillerato'), ('terciario', 'Terciario'), ('universitario', 'Universitario'), ('posgrado', 'Posgrado / Master')], max_length=30)),
                ('es_confidencial', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('activa', 'Activa'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField()),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas', to='ofertas.categoriaoferta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
