# Generated by Django 6.0.6 on 2026-06-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_remove_oferta_requisitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='experiencia_requerida',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
