# Generated by Django 5.2.15 on 2026-06-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0004_oferta_motivo_rechazo_alter_oferta_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Oferta',
                'verbose_name_plural': 'Tipos de Ofertas',
            },
        ),
        migrations.AlterField(
            model_name='categoriaoferta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
