# Generated by Django 5.2.15 on 2026-06-25 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0005_tipooferta_alter_categoriaoferta_id_alter_oferta_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='tipo_oferta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas', to='ofertas.tipooferta'),
        ),
    ]
