# Generated by Django 5.2.15 on 2026-06-25 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0006_oferta_tipo_oferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='ofertas.tipooferta')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'unique_together': {('nombre', 'tipo_oferta')},
            },
        ),
    ]
