# Generated by Django 6.0.5 on 2026-07-02 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0007_habilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas_por_categoria', to='ofertas.categoriaoferta'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo_oferta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas_por_tipo', to='ofertas.tipooferta'),
        ),
    ]
