# Generated by Django 6.0.7 on 2026-08-04 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('ofertas', '0008_alter_oferta_categoria_alter_oferta_tipo_oferta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria'),
        ),
        migrations.AlterUniqueTogether(
            name='habilidad',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='habilidad',
            name='tipo_oferta',
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo_oferta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.tipooferta'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='experiencia_requerida',
            field=models.CharField(choices=[('sin-experiencia', 'Sin experiencia'), ('menos-1', 'Menos de 1 año'), ('1-2', '1-2 años'), ('2-3', '2-3 años'), ('3-5', '3-5 años'), ('5+', '5+ años')], default='sin-experiencia', max_length=20),
        ),
        migrations.DeleteModel(
            name='CategoriaOferta',
        ),
        migrations.DeleteModel(
            name='Habilidad',
        ),
        migrations.DeleteModel(
            name='TipoOferta',
        ),
    ]
