# Generated by Django 6.0.6 on 2026-09-11 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0009_alter_oferta_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='tipo_oferta',
        ),
    ]
