# Generated by Django 6.1 on 2026-09-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0010_remove_oferta_tipo_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='habilidades_blandas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='oferta',
            name='habilidades_duras',
            field=models.TextField(blank=True, default=''),
        ),
    ]
