# Generated by Django 6.1 on 2026-09-30 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0013_proteger_categoria_en_uso'),
        ('usuarios', '0014_drop_columna_estado_huerfana'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaFavorita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorita_por', to='ofertas.oferta')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritas', to='usuarios.postulante')),
            ],
            options={
                'verbose_name': 'Oferta favorita',
                'verbose_name_plural': 'Ofertas favoritas',
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(fields=('postulante', 'oferta'), name='unico_postulante_oferta_favorita')],
            },
        ),
    ]
