# Generated by Django 6.0.5 on 2026-06-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderacion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditoriaValidacion',
        ),
    ]
