# Generated by Django 5.2.17 on 2026-09-30 01:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ofertas', '0013_proteger_categoria_en_uso'),
        ('usuarios', '0014_drop_columna_estado_huerfana'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoCompatibilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cache_key', models.CharField(max_length=64, unique=True)),
                ('estado', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('rate_limited', 'Rate limited'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('perfil_cv_version', models.PositiveIntegerField()),
                ('perfil_oferta_version', models.PositiveIntegerField()),
                ('perfil_cv_hash', models.CharField(max_length=64)),
                ('perfil_oferta_hash', models.CharField(max_length=64)),
                ('rubric_version', models.CharField(default='match-rubric.v1', max_length=64)),
                ('matcher_prompt_version', models.CharField(default='match-rubric.v1', max_length=64)),
                ('model_version', models.CharField(default='jev-latest', max_length=120)),
                ('resultado', models.JSONField(blank=True, null=True)),
                ('match_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coverage_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('confidence_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_match', to='ofertas.oferta')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_match', to='usuarios.postulante')),
            ],
            options={
                'indexes': [models.Index(fields=['postulante', 'oferta', 'estado'], name='matching_re_postula_c69c51_idx')],
            },
        ),
    ]
