# Generated by Django 6.0.6 on 2026-06-06 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_managers_remove_usuario_cuit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulante',
            name='nombre_completo',
        ),
    ]
