# Generated by Django 6.0.6 on 2026-06-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_managers_remove_usuario_cuit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferente',
            name='anio_fundacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferente',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/banners/'),
        ),
        migrations.AddField(
            model_name='oferente',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferente',
            name='industria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='oferente',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logos/'),
        ),
        migrations.AddField(
            model_name='oferente',
            name='sitio_web',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='oferente',
            name='tamano_empresa',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 empleados'), ('11-50', '11-50 empleados'), ('51-200', '51-200 empleados'), ('201-1000', '201-1000 empleados'), ('1000+', 'Más de 1000 empleados')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='oferente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oferente',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
