# Generated by Django 6.0.5 on 2026-06-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_oferente_anio_fundacion_oferente_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='postulante',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='postulante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postulante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
