# Generated by Django 6.0.6 on 2026-06-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_postulante_direccion_postulante_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferente',
            name='estado_validacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('aprobado', 'Aprobada'), ('rechazado', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
