# Generated by Django 6.0.5 on 2026-06-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_oferente_estado_validacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferente',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de validación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
