# Generated by Django 5.2.15 on 2026-07-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_oferente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='postulantes/cv/'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='cv_fecha_carga',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
