# Generated by Django 6.0.6 on 2026-08-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_oferente_estado'),
        ('usuarios', '0009_postulante_cv_postulante_cv_fecha_carga'),
    ]

    operations = [
    ]
