# Generated by Django 6.0.7 on 2026-08-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_merge_20260804_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferente',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
