# Generated by Django 6.0.6 on 2026-09-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_oferente_motivo_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferente',
            name='estado_validacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('aprobado', 'Aprobada'), ('rechazado', 'Rechazada')], default='rechazado', max_length=20),
        ),
    ]
