# Generated by Django 6.0.6 on 2026-09-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_oferente_estado_validacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferente',
            name='estado_validacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('aprobado', 'Aprobada'), ('rechazado', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
