# Generated by Django 6.0.5 on 2026-09-17 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0014_drop_columna_estado_huerfana'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=12)),
                ('respuesta', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('respondido_en', models.DateTimeField(blank=True, null=True)),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_cv', to='usuarios.postulante')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
