# Generated by Django 5.2.17 on 2026-09-30 01:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0002_unico_analisis_pendiente'),
        ('ofertas', '0013_proteger_categoria_en_uso'),
        ('usuarios', '0014_drop_columna_estado_huerfana'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoRecepcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventoSalida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('extract_cv', 'Extract CV'), ('extract_offer', 'Extract offer'), ('match', 'Match')], max_length=24)),
                ('clave_idempotencia', models.CharField(max_length=180, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('error', 'Error')], default='pending', max_length=16)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('proximo_intento_en', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.JSONField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('schema_version', models.CharField(default='candidate-profile.v1', max_length=64)),
                ('estado', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error'), ('proposal_ready', 'Proposal ready')], default='pending', max_length=20)),
                ('origen', models.CharField(default='extraction', max_length=24)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('analisis_fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ia.analisiscv')),
                ('postulante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_ia', to='usuarios.postulante')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilOferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.JSONField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('schema_version', models.CharField(default='job-offer.v1', max_length=64)),
                ('estado', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error'), ('proposal_ready', 'Proposal ready')], default='pending', max_length=20)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('oferta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_ia', to='ofertas.oferta')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoExtraccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('clave_idempotencia', models.CharField(max_length=180, unique=True)),
                ('tipo', models.CharField(choices=[('candidate_cv', 'Candidate CV'), ('job_offer', 'Job offer')], max_length=20)),
                ('source_hash', models.CharField(max_length=64)),
                ('remote_job_id', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('accepted', 'Accepted'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error'), ('delivery_unknown', 'Delivery unknown')], default='pending', max_length=24)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('analisis_cv', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajo_extraccion', to='ia.analisiscv')),
                ('oferta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_extraccion', to='ofertas.oferta')),
            ],
        ),
        migrations.CreateModel(
            name='VersionPerfilCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('contenido', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('origen', models.CharField(max_length=24)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='ia.perfilcv')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('perfil', 'version'), name='ia_perfil_cv_version_unica')],
            },
        ),
        migrations.CreateModel(
            name='VersionPerfilOferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('contenido', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='ia.perfiloferta')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('perfil', 'version'), name='ia_perfil_oferta_version_unica')],
            },
        ),
    ]
