# Generated by Django 5.2.17 on 2026-09-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0003_eventorecepcion_eventosalida_perfilcv_perfiloferta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajoextraccion',
            name='cv_snapshot',
            field=models.FileField(blank=True, null=True, upload_to='ia/extraction_snapshots/'),
        ),
    ]
