# Generated by Django 5.2.17 on 2026-09-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0004_trabajoextraccion_cv_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajoextraccion',
            name='prompt_version',
            field=models.CharField(default='extraction.v1', max_length=64),
        ),
    ]
