# Generated by Django 5.2.17 on 2026-09-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0005_trabajoextraccion_prompt_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosalida',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('extract_cv', 'Extract CV'),
                    ('extract_offer', 'Extract offer'),
                    ('normalize_profile', 'Normalize profile'),
                    ('match', 'Match'),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name='trabajoextraccion',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('candidate_cv', 'Candidate CV'),
                    ('job_offer', 'Job offer'),
                    ('normalize_profile', 'Normalize candidate profile'),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='trabajoextraccion',
            name='profile_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajoextraccion',
            name='profile_version_base',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
