# Generated by Django 6.0.5 on 2026-06-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='horario',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Hibrido', 'Hibrido')], default='Presencial', max_length=20),
        ),
        migrations.AddField(
            model_name='curso',
            name='url_externa',
            field=models.URLField(blank=True, null=True),
        ),
    ]
