# Generated by Django 6.0.7 on 2026-08-04 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('cursos', '0004_alter_categoria_id_alter_curso_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
