# Generated by Django 6.0.7 on 2026-08-31 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habilidad',
            unique_together={('nombre', 'categoria')},
        ),
    ]
