# Generated by Django 6.0.6 on 2026-09-03 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_habilidad_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
    ]
