# Generated by Django 6.0.6 on 2026-09-03 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_alter_categoria_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habilidad',
            unique_together={('nombre', 'tipo_oferta')},
        ),
        migrations.RemoveField(
            model_name='habilidad',
            name='categoria',
        ),
    ]
