# Generated by Django 6.0.6 on 2026-09-11 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0004_alter_habilidad_unique_together_and_more'),
        ('ofertas', '0010_remove_oferta_tipo_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidad',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='habilidad',
            unique_together={('nombre', 'categoria')},
        ),
        migrations.RemoveField(
            model_name='habilidad',
            name='tipo_oferta',
        ),
        migrations.DeleteModel(
            name='TipoOferta',
        ),
    ]
